apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-6pbp
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-6pbp
    app.kubernetes.io/part-of: tkrw-pr712-0075-0066-app
  name: devfile-sample-6pbp
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-6pbp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-6pbp
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-6pbp@sha256:c0a02614adf428f432bdc7f328ea9372f590d9eba9642e8cf08824bb711f4bd0
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
